# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MacOSSimpleIntegrationSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AppNexusSDK', '9.0.0'
end

target 'SimpleIntegrationSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AppNexusSDK', '9.0.0'
end
